import type { Product } from '../types/product'

export const products: Product[] = [
  {
    logo: '🎨',
    name: 'BuilderTudo Studio',
    description: 'Divisão de desenvolvimento sob demanda: sites, sistemas, identidade visual e soluções digitais.',
    category: 'Desenvolvimento Digital',
    technologies: ['React', 'TypeScript', 'UX/UI'],
    status: 'Ativo',
    href: '#studio',
  },
  {
    logo: '🛡️',
    name: 'BlindCare',
    description: 'Plataforma de gestão e cuidado com foco em segurança, acompanhamento e experiência premium.',
    category: 'Saúde',
    technologies: ['React', 'TypeScript', 'Supabase', 'OpenAI'],
    status: 'Ativo',
    routeKey: 'blindcare',
    featured: true,
  },
  {
    logo: '📋',
    name: 'PrevPro',
    description: 'Solução inteligente para prevenção, organização e controle de processos críticos.',
    category: 'Compliance',
    technologies: ['Next.js', 'Node.js', 'Firebase', 'Cloudflare'],
    status: 'Ativo',
    routeKey: 'prevpro',
    featured: true,
  },
  {
    logo: '🎙️',
    name: 'VoxCraft',
    description: 'Tecnologia de voz e comunicação para experiências digitais mais humanas e eficientes.',
    category: 'IA & Voz',
    technologies: ['React', 'Node.js', 'OpenAI', 'APIs'],
    status: 'Ativo',
    routeKey: 'voxcraft',
    featured: true,
  },
  {
    logo: '✍️',
    name: 'ContentFy',
    description: 'Plataforma para criação, gestão e distribuição de conteúdo em escala.',
    category: 'Marketing Tech',
    technologies: ['React', 'TypeScript', 'OpenAI', 'Vercel'],
    status: 'Em evolução',
    routeKey: 'contentfy',
    featured: true,
  },
  {
    logo: '⛽',
    name: 'FuelMaster',
    description: 'Sistema de controle e inteligência operacional para gestão de combustível e frota.',
    category: 'Logística',
    technologies: ['React', 'Node.js', 'Supabase'],
    status: 'Ativo',
    routeKey: 'fuelmaster',
  },
  {
    logo: '🔍',
    name: 'AuditeIA',
    description: 'Auditoria inteligente com IA para análise, conformidade e tomada de decisão.',
    category: 'Inteligência Artificial',
    technologies: ['Python', 'OpenAI', 'APIs', 'Cloudflare'],
    status: 'Ativo',
    routeKey: 'auditeia',
  },
  {
    logo: '🏗️',
    name: 'ConstruFy',
    description: 'Plataforma digital para construção civil, obras e gestão de projetos.',
    category: 'Construção',
    technologies: ['React', 'TypeScript', 'Firebase'],
    status: 'Ativo',
    routeKey: 'construfy',
  },
  {
    logo: '⚖️',
    name: 'JurisMind',
    description: 'Inteligência jurídica para organização documental, fluxos e produtividade legal.',
    category: 'Jurídico',
    technologies: ['Next.js', 'OpenAI', 'Supabase'],
    status: 'Ativo',
    routeKey: 'jurismind',
  },
  {
    logo: '🦷',
    name: 'ProOdonto Smart',
    description: 'Ecossistema smart para clínicas odontológicas com gestão e experiência do paciente.',
    category: 'Saúde',
    technologies: ['React', 'TypeScript', 'Firebase'],
    status: 'Ativo',
    routeKey: 'proodonto',
  },
  {
    logo: '🚀',
    name: 'Fui App',
    description: 'Solução digital inovadora para jornadas, mobilidade e experiências conectadas.',
    category: 'Mobilidade',
    technologies: ['React Native', 'Node.js', 'APIs'],
    status: 'Em evolução',
    routeKey: 'fui',
  },
  {
    logo: '✨',
    name: 'Copygênio',
    description: 'Plataforma de copywriting e conteúdo inteligente com IA para marcas e negócios digitais.',
    category: 'Marketing Tech',
    technologies: ['React', 'OpenAI', 'TypeScript', 'Vercel'],
    status: 'Ativo',
    routeKey: 'copygenio',
  },
]

export const featuredProducts = products.filter((product) => product.featured)

export const footerProductNames = [
  'BlindCare',
  'PrevPro',
  'VoxCraft',
  'ContentFy',
  'FuelMaster',
  'AuditeIA',
  'ProOdonto Smart',
  'Copygênio',
  'Fui App',
] as const

export const footerProducts = footerProductNames
  .map((name) => products.find((product) => product.name === name))
  .filter((product): product is Product => product !== undefined)
