export type ScreenId =
  | 'framework'
  | 'command-center'
  | 'products-hub'
  | 'crm'
  | 'studio'
  | 'tasks'
  | 'analytics'
  | 'ai-center'
  | 'settings'
  | 'deploy'
  | 'ceo-copilot'
  | 'framework-health'

export type ScreenMeta = {
  id: ScreenId
  name: string
  demoUrl: string
  category: 'business-os' | 'framework' | 'platform'
}

export type ScreenshotFormat = 'webp' | 'png'

/** Real screenshot path — generated by `npm run capture:screenshots` from Business OS. */
export function getScreenImagePath(id: ScreenId, format: ScreenshotFormat = 'webp') {
  return `/showcase/business-os/${id}.${format}`
}

export function getProductImagePath(slug: string, format: ScreenshotFormat = 'webp') {
  return `/showcase/products/${slug}.${format}`
}

/** Business OS routes used by the capture script. */
export const SCREEN_CAPTURE_ROUTES: Record<ScreenId, string> = {
  'command-center': '/',
  'products-hub': '/products',
  crm: '/crm',
  studio: '/studio',
  tasks: '/tasks',
  analytics: '/analytics',
  'ai-center': '/ai-center',
  framework: '/framework',
  'framework-health': '/framework',
  settings: '/settings',
  'ceo-copilot': '/ai-center/ceo',
  deploy: '/framework',
}

export const PLATFORM_SCREENS: Record<ScreenId, ScreenMeta> = {
  framework: {
    id: 'framework',
    name: 'Framework',
    demoUrl: '/framework',
    category: 'framework',
  },
  'command-center': {
    id: 'command-center',
    name: 'Command Center',
    demoUrl: '/',
    category: 'business-os',
  },
  'products-hub': {
    id: 'products-hub',
    name: 'Products Hub',
    demoUrl: '/products',
    category: 'business-os',
  },
  crm: {
    id: 'crm',
    name: 'CRM',
    demoUrl: '/crm',
    category: 'business-os',
  },
  studio: {
    id: 'studio',
    name: 'Studio',
    demoUrl: '/studio',
    category: 'business-os',
  },
  tasks: {
    id: 'tasks',
    name: 'Tasks',
    demoUrl: '/tasks',
    category: 'business-os',
  },
  analytics: {
    id: 'analytics',
    name: 'Analytics',
    demoUrl: '/analytics',
    category: 'business-os',
  },
  'ai-center': {
    id: 'ai-center',
    name: 'AI Center',
    demoUrl: '/ai-center',
    category: 'business-os',
  },
  settings: {
    id: 'settings',
    name: 'Settings',
    demoUrl: '/settings',
    category: 'business-os',
  },
  deploy: {
    id: 'deploy',
    name: 'Deploy Timeline',
    demoUrl: '/framework',
    category: 'business-os',
  },
  'ceo-copilot': {
    id: 'ceo-copilot',
    name: 'CEO Copilot',
    demoUrl: '/ai-center/ceo',
    category: 'business-os',
  },
  'framework-health': {
    id: 'framework-health',
    name: 'Framework Health',
    demoUrl: '/framework',
    category: 'framework',
  },
}

export const HERO_SHOWCASE_SEQUENCE: ScreenId[] = [
  'framework',
  'command-center',
  'ai-center',
  'crm',
  'products-hub',
  'analytics',
  'studio',
  'deploy',
]

/** Screens confirmed available — updated by capture script into showcase/manifest.json */
export const DEFAULT_AVAILABLE_SCREENS: ScreenId[] = []
