import { PRODUCT_CATALOG } from './products'
import { mergeEnrichment, type CaseStudyEnrichment } from './case-study-builders'
import type { CaseStudyContent } from '../types/case-study'

type CaseStudyEvolutionItem = CaseStudyEnrichment['evolution'][number]

function evolutionItems(items: Array<[string, string, 'done' | 'in-progress' | 'planned', string]>): CaseStudyEvolutionItem[] {
  return items.map(([phase, title, status, description]) => ({ phase, title, status, description }))
}

const ENRICHMENTS: Record<string, CaseStudyEnrichment> = {
  contentfy: {
    industry: 'Marketing Technology',
    headline: 'Scaling on-brand content without losing governance',
    summary: 'How BuilderTudo engineered an AI-native content platform with RAG-based brand knowledge and human-in-the-loop quality control.',
    problemTitle: 'Brand voice breaks at scale',
    problemNarrative: 'Marketing teams adopted generic AI writing tools and immediately hit a wall: every channel sounded different, SEO quality dropped, and legal review became a bottleneck. There was no governed pipeline — only disconnected prompts and spreadsheets.',
    painPoints: ['Inconsistent brand voice across channels', 'No audit trail for AI-generated copy', 'SEO quality degraded at volume', 'Review cycles blocked publishing velocity'],
    solutionTitle: 'Governed content pipeline with brand RAG',
    solutionNarrative: 'ContentFy was built on AI-OS with a structured knowledge core for brand guidelines. Copy generation routes through guardrails, human review gates and a multi-channel distribution engine — shipping 3× faster without sacrificing voice.',
    approach: ['Brand knowledge core with RAG embeddings', 'Human-in-the-loop review before publish', 'Golden Screens validated campaign workflows', 'Edge runtime for streaming AI responses'],
    architectureDecisions: ['Separated generation from distribution in Engine workflows', 'Brand context injected at AI-OS routing layer', 'Golden Screens approved before full build'],
    results: [{ value: '3×', label: 'Faster content production' }, { value: '100%', label: 'Brand review coverage' }, { value: '88%', label: 'Framework Health' }],
    learnings: ['Brand consistency requires structured knowledge core, not bigger prompts', 'Human-in-the-loop improves perceived quality 3×', 'SEO metadata must be generated alongside copy, not after'],
    evolution: [
      { phase: '2025 Q3', title: 'Content Editor Golden Screen', status: 'done', description: 'Validated editor UX and review flow before backend build.' },
      { phase: '2025 Q4', title: 'AI-OS brand pipeline', status: 'done', description: 'RAG knowledge core and guardrails in production.' },
      { phase: '2026 Q1', title: 'Multi-channel publishing', status: 'in-progress', description: 'Engine workflows for cross-channel distribution.' },
      { phase: '2026 Q2', title: 'Brand voice profiles', status: 'planned', description: 'Per-client voice tuning without retraining.' },
    ],
    publishedAt: '2026-01-15',
  },
  fui: {
    industry: 'Mobility',
    headline: 'Building offline-first mobility without reinventing the location stack',
    summary: 'Engineering a React Native mobility platform with event-driven location, partner APIs and privacy-by-design from the first sprint.',
    problemTitle: 'Mobility products fail on connectivity and privacy',
    problemNarrative: 'Most mobility MVPs treat location as an afterthought — brittle tracking, no offline mode, and privacy policies bolted on late. Partners cannot integrate without custom one-off APIs.',
    painPoints: ['Tracking breaks in low-connectivity zones', 'Location privacy not architected early', 'Partner integrations require custom work', 'Journey UX inconsistent across platforms'],
    solutionTitle: 'Event-driven mobility core on Framework',
    solutionNarrative: 'Fui centralizes location events in Engine, exposes partner webhooks as first-class APIs, and uses Golden Screens to validate journey maps before native implementation — reducing rework across iOS and Android.',
    approach: ['Offline-first journey state sync', 'Privacy controls at data model level', 'Partner API gateway via Engine', 'Shared Golden Screens for cross-platform UX'],
    architectureDecisions: ['Event-sourced location pipeline', 'React Native monorepo sharing Framework components', 'Partner sandbox before production keys'],
    results: [{ value: '72%', label: 'Framework Health' }, { value: '<200ms', label: 'Location event latency target' }, { value: '1', label: 'Codebase for iOS & Android' }],
    learnings: ['Offline-first is non-negotiable for mobility', 'Location privacy must be designed before first GPS call', 'Partner APIs need versioning from day one'],
    evolution: evolutionItems([
      ['2025 Q4', 'Journey Map Golden Screen', 'done', 'Stakeholder alignment before native build.'],
      ['2026 Q1', 'Location event engine', 'in-progress', 'WebSocket + offline queue implementation.'],
      ['2026 Q2', 'Partner integrations', 'planned', 'Webhook gateway and API keys.'],
      ['2026 Q3', 'Store launch', 'planned', 'iOS and Android production release.'],
    ]),
    publishedAt: '2026-02-01',
  },
  jurismind: {
    industry: 'Legal Technology',
    headline: 'Legal-grade AI without citation hallucinations',
    summary: 'How JurisMind combines RAG, strict guardrails and audit trails for document intelligence that legal teams can trust.',
    problemTitle: 'Legal AI that lawyers cannot defend in court',
    problemNarrative: 'Legal teams experimented with general-purpose LLMs and faced hallucinated citations, no audit trail, and workflows that did not map to case structure. Compliance risk outweighed productivity gains.',
    painPoints: ['Hallucinated legal citations', 'No audit trail for AI-assisted research', 'Documents scattered across tools', 'Workflows disconnected from case structure'],
    solutionTitle: 'Citation-accurate RAG with legal guardrails',
    solutionNarrative: 'JurisMind embeds documents in a governed knowledge core, enforces citation validation in AI-OS, and maps workflows to case entities — delivering 80% faster review with defensible outputs.',
    approach: ['Document embedding pipeline with version control', 'Citation validation guardrails in AI-OS', 'Case-centric workflow model', 'Business OS CRM sync for client matters'],
    architectureDecisions: ['Supabase RLS for matter-level isolation', 'Separate read vs. generate permissions', 'Immutable audit log for AI queries'],
    results: [{ value: '80%', label: 'Time saved on document review' }, { value: '91%', label: 'Framework Health' }, { value: '100%', label: 'Citation validation on outputs' }],
    learnings: ['Legal data requires guardrails, not disclaimers', 'Citation accuracy is non-negotiable for adoption', 'Workflow must mirror how lawyers think about matters'],
    evolution: evolutionItems([
      ['2025 Q2', 'Document Vault MVP', 'done', 'Multi-tenant vault with search.'],
      ['2025 Q4', 'RAG research panel', 'done', 'Citation-validated AI research in production.'],
      ['2026 Q1', 'Multi-jurisdiction rules', 'in-progress', 'Jurisdiction-aware guardrail packs.'],
      ['2026 Q2', 'Client portal', 'planned', 'Secure client document sharing.'],
    ]),
    publishedAt: '2025-11-20',
  },
  blindcare: {
    industry: 'Healthcare',
    headline: 'Healthcare SaaS with LGPD baked into the architecture',
    summary: 'Building a care coordination platform with 99.9% uptime targets, predictive alerts and compliance at the data model — not the policy PDF.',
    problemTitle: 'Care coordination fragmented across tools',
    problemNarrative: 'Families, caregivers and clinics coordinated care through phone calls and spreadsheets. No unified view, delayed alerts, and patient data handled without consistent LGPD controls.',
    painPoints: ['No single source of truth for care plans', 'Alert fatigue without prioritization', 'LGPD compliance as afterthought', 'Uptime requirements unmet by generic tools'],
    solutionTitle: 'Multi-tenant care OS with AI copilot',
    solutionNarrative: 'BlindCare unifies dashboards, family portals and alert centers with AI-OS risk scoring. Architecture enforces tenant isolation, audit logging and 99.9% uptime patterns from Framework healthcare Golden Screens.',
    approach: ['LGPD-compliant multi-tenant Supabase model', 'AI risk scoring with human escalation', 'Alert prioritization engine', 'Accessibility-first Golden Screens'],
    architectureDecisions: ['Healthcare data never crosses tenant boundaries', 'Predictive models run on anonymized aggregates', 'Failover patterns tested in Framework runtime'],
    results: [{ value: '40%', label: 'Faster caregiver onboarding' }, { value: '99.9%', label: 'Uptime architecture target' }, { value: '94%', label: 'Framework Health' }],
    learnings: ['Healthcare requires 99.9% uptime from architecture, not SLA text', 'LGPD compliance must be in the schema', 'Predictive alerts need human override paths'],
    evolution: evolutionItems([
      ['2025 Q1', 'Care Dashboard live', 'done', 'Production multi-tenant rollout.'],
      ['2025 Q3', 'Predictive alerts v1', 'done', 'Risk scoring with caregiver notifications.'],
      ['2026 Q1', 'Mobile caregiver app', 'in-progress', 'React Native field app.'],
      ['2026 Q2', 'Insurance integrations', 'planned', 'Claims and eligibility APIs.'],
    ]),
    publishedAt: '2025-10-08',
  },
  professoria: {
    industry: 'Education Technology',
    headline: 'Adaptive tutoring that teachers still control',
    summary: 'Institutional-scale personalization with AI-OS pacing algorithms and mandatory teacher oversight — engagement up 40% without black-box tutoring.',
    problemTitle: 'One-size-fits-all breaks at institutional scale',
    problemNarrative: 'Schools and training providers could not personalize learning paths for hundreds of students. Generic AI tutors lacked pedagogical guardrails and teacher visibility.',
    painPoints: ['Fixed curricula ignore student pace', 'AI tutors without teacher oversight', 'No LMS integration path', 'Engagement drops after week two'],
    solutionTitle: 'Teacher-governed adaptive engine',
    solutionNarrative: 'ProfessorIA combines adaptive pacing in AI-OS with teacher dashboards for override and review. Golden Screens aligned educators before engineering scaled the lesson builder.',
    approach: ['Adaptive pacing with teacher approval gates', 'Progress analytics per cohort', 'Firebase real-time sync for classrooms', 'LMS integration roadmap in Engine'],
    architectureDecisions: ['Teacher role has veto on AI recommendations', 'Offline lesson caching for low-bandwidth schools', 'Separate student vs. admin data realms'],
    results: [{ value: '40%', label: 'Higher student engagement' }, { value: '76%', label: 'Framework Health' }, { value: '3', label: 'Golden Screens validated' }],
    learnings: ['Adaptive pacing increases engagement when teachers retain control', 'Offline lesson sync is critical in emerging markets', 'LMS hooks must be planned before content model freezes'],
    evolution: evolutionItems([
      ['2025 Q4', 'Student Dashboard Golden Screen', 'done', 'UX validated with pilot school.'],
      ['2026 Q1', 'Adaptive curriculum engine', 'in-progress', 'AI-OS pacing in beta classrooms.'],
      ['2026 Q2', 'Institutional analytics', 'planned', 'Cohort and outcome dashboards.'],
      ['2026 Q3', 'LMS integrations', 'planned', 'Canvas and Moodle connectors.'],
    ]),
    publishedAt: '2026-01-28',
  },
  voxcraft: {
    industry: 'AI & Voice',
    headline: 'Sub-200ms voice APIs that enterprises actually adopt',
    summary: 'API-first voice platform with streaming pipeline, usage analytics and SDK roadmap — engineered for product teams, not demo videos.',
    problemTitle: 'Voice feels magical in demos, fragile in production',
    problemNarrative: 'Product teams integrated voice through fragmented APIs with unpredictable latency and no observability. Enterprise buyers demanded SLAs, multi-language support and clear pricing — none of which bolt-on tools provided.',
    painPoints: ['Latency spikes above conversational threshold', 'No unified analytics for voice usage', 'SDK gaps block enterprise adoption', 'Streaming architecture treated as optional'],
    solutionTitle: 'Streaming-first voice microservices',
    solutionNarrative: 'VoxCraft ships a sub-200ms pipeline with WebSocket streaming, API console and voice studio on Framework. Engine handles queueing and webhook delivery; Golden Screens validated admin UX before public API.',
    approach: ['Streaming WebSocket API as primary interface', 'Voice studio for non-developer tuning', 'Usage analytics with per-tenant quotas', 'Enterprise SDK on public roadmap'],
    architectureDecisions: ['API-first — UI is a client of the same API', 'Latency budget enforced in CI load tests', 'Model routing abstracted in AI-OS'],
    results: [{ value: '<200ms', label: 'P95 latency target' }, { value: '89%', label: 'Framework Health' }, { value: 'API-first', label: 'Architecture pattern' }],
    learnings: ['Latency under 200ms is the quality threshold for voice', 'API-first drives adoption faster than UI-first', 'Usage analytics must ship with v1, not v3'],
    evolution: evolutionItems([
      ['2025 Q2', 'Voice API v1', 'done', 'Production streaming endpoints.'],
      ['2025 Q4', 'Voice Studio', 'done', 'Self-serve voice configuration.'],
      ['2026 Q1', 'Multi-language voices', 'in-progress', 'Locale routing in AI-OS.'],
      ['2026 Q2', 'Enterprise SDK', 'planned', 'Node and Python client libraries.'],
    ]),
    publishedAt: '2025-09-14',
  },
  prevenpro: {
    industry: 'Compliance & Risk',
    headline: 'Real-time compliance that prevents audit failures',
    summary: 'Multi-tenant compliance platform with anomaly detection, automated reporting and 60% fewer audit failures — built for regulated operations.',
    problemTitle: 'Audit failures from manual process control',
    problemNarrative: 'Operations teams tracked critical processes in spreadsheets. Alerts arrived too late, audit evidence was scattered, and multi-site organizations had no isolated tenant model.',
    painPoints: ['Manual compliance checks', 'Delayed anomaly detection', 'Audit evidence not centralized', 'Multi-site data leakage risk'],
    solutionTitle: 'Real-time compliance engine',
    solutionNarrative: 'PrevenPro automates scoring, detects anomalies via AI-OS and generates audit packs on schedule. Firebase multi-tenant isolation and Cloudflare edge protection ship as defaults.',
    approach: ['Real-time alert engine', 'Compliance scoring models', 'Auto-generated audit reports', 'Framework Health visibility in Business OS'],
    architectureDecisions: ['Tenant isolation at Firebase rules level', 'Alert deduplication to prevent fatigue', 'Immutable audit event stream'],
    results: [{ value: '60%', label: 'Fewer audit failures' }, { value: '92%', label: 'Framework Health' }, { value: 'Real-time', label: 'Alert delivery' }],
    learnings: ['Real-time alerts reduce audit failures more than quarterly reviews', 'Multi-tenant isolation is essential for enterprise compliance', 'Auto-reports must map to auditor vocabulary'],
    evolution: evolutionItems([
      ['2025 Q1', 'Process Monitor live', 'done', 'Core monitoring in production.'],
      ['2025 Q3', 'Audit automation', 'done', 'Scheduled compliance report generation.'],
      ['2026 Q1', 'Multi-tenant SaaS', 'in-progress', 'Enterprise tenant onboarding.'],
      ['2026 Q2', 'Compliance reports v2', 'planned', 'Custom auditor templates.'],
    ]),
    publishedAt: '2025-08-22',
  },
  fuelmaster: {
    industry: 'Logistics & Fleet',
    headline: 'Fleet intelligence when IoT meets offline reality',
    summary: 'Fuel and fleet operations platform with Engine automation, consumption prediction and IoT-ready sync — dashboards operators trust.',
    problemTitle: 'Fleet ops blind without real-time fuel intelligence',
    problemNarrative: 'Fleet managers relied on delayed fuel reports and manual route planning. IoT sensor data existed but did not reach dashboards reliably — especially when connectivity dropped.',
    painPoints: ['Delayed fuel consumption visibility', 'Route planning disconnected from live data', 'IoT integration fragile offline', 'No unified fleet command view'],
    solutionTitle: 'IoT-ready fleet command center',
    solutionNarrative: 'FuelMaster combines real-time Supabase sync, Engine workflow automation and consumption prediction. Golden Screens validated fleet overview before IoT ingestion scaled.',
    approach: ['Real-time fleet telemetry dashboard', 'Engine rules for fuel anomaly alerts', 'Offline-tolerant sensor sync queue', 'Route planner with prediction models'],
    architectureDecisions: ['Sensor data buffered locally when offline', 'Prediction models trained on tenant-scoped data only', 'Workflow automation separate from UI layer'],
    results: [{ value: '87%', label: 'Framework Health' }, { value: 'Real-time', label: 'Fleet dashboard sync' }, { value: 'IoT-ready', label: 'Ingestion architecture' }],
    learnings: ['IoT integration requires robust offline sync', 'Fleet ops need single-pane dashboards, not reports', 'Fuel anomaly alerts must avoid false-positive storms'],
    evolution: evolutionItems([
      ['2025 Q2', 'Fleet Overview live', 'done', 'Production dashboard for pilot fleets.'],
      ['2025 Q4', 'Fuel analytics v1', 'done', 'Consumption trends and exports.'],
      ['2026 Q1', 'IoT sensor integration', 'in-progress', 'Telemetry ingestion pipeline.'],
      ['2026 Q2', 'Route optimization v2', 'planned', 'ML-assisted route suggestions.'],
    ]),
    publishedAt: '2025-12-05',
  },
  diagramafy: {
    industry: 'Developer Tools',
    headline: 'Architecture docs that stay aligned with reality',
    summary: 'AI-assisted diagramming with Mermaid export and auto-layout — hours saved per diagram, fewer stale architecture wikis.',
    problemTitle: 'Architecture diagrams rot within weeks',
    problemNarrative: 'Engineering teams spent hours in diagram tools that did not integrate with code or docs. AI could sketch ideas but output was not editable or exportable to engineering standards like Mermaid.',
    painPoints: ['Diagrams diverge from implementation', 'Manual layout consumes senior time', 'No Mermaid export path', 'Collaboration locked in static files'],
    solutionTitle: 'AI canvas with engineering-grade export',
    solutionNarrative: 'DiagramaFy generates diagrams from natural language, applies auto-layout and exports to Mermaid — keeping architecture artifacts in sync with how engineers actually work.',
    approach: ['Text-to-diagram via AI-OS', 'Auto-layout engine', 'Mermaid export pipeline', 'Template library from Golden Screens'],
    architectureDecisions: ['Canvas state serializable to Mermaid AST', 'AI suggestions never auto-commit without review', 'Templates versioned in Framework package'],
    results: [{ value: 'Hours', label: 'Saved per complex diagram' }, { value: '81%', label: 'Framework Health' }, { value: 'Mermaid', label: 'Export compatibility' }],
    learnings: ['Developers want Mermaid compatibility, not proprietary formats', 'Auto-layout saves senior architect time disproportionately', 'AI diagrams need diff-friendly exports'],
    evolution: evolutionItems([
      ['2025 Q4', 'Canvas Editor beta', 'done', 'Core editing experience shipped.'],
      ['2026 Q1', 'Auto-layout engine', 'in-progress', 'Constraint-based layout solver.'],
      ['2026 Q2', 'Mermaid export', 'planned', 'Round-trip Mermaid import/export.'],
      ['2026 Q3', 'Team workspaces', 'planned', 'Shared libraries and review.'],
    ]),
    publishedAt: '2026-02-10',
  },
  respondfy: {
    industry: 'Customer Success',
    headline: 'Support automation without brand damage',
    summary: 'Omnichannel response engine with sentiment routing and mandatory human review — CSAT up, brand incidents down.',
    problemTitle: 'Auto-replies that hurt brand trust',
    problemNarrative: 'Support teams turned on generic auto-responders and immediately saw CSAT drop. Sentiment was misread, escalations were late, and brand voice varied by channel.',
    painPoints: ['Generic auto-responses erode trust', 'Sentiment misclassification', 'No human review before send', 'Channels siloed in separate inboxes'],
    solutionTitle: 'Governed response engine',
    solutionNarrative: 'RespondFy routes messages through sentiment analysis, brand voice templates and human approval queues. AI-OS handles generation; Engine orchestrates omnichannel delivery.',
    approach: ['Sentiment-based routing rules', 'Brand voice template library', 'Human review queue for edge cases', 'Omnichannel inbox unification'],
    architectureDecisions: ['No auto-send for negative sentiment', 'Template versioning with rollback', 'CRM sync as async Engine jobs'],
    results: [{ value: '↑ CSAT', label: 'With sentiment routing' }, { value: '84%', label: 'Framework Health' }, { value: '0', label: 'Unreviewed negative auto-sends' }],
    learnings: ['Human review loop prevents brand damage', 'Sentiment routing improves CSAT more than faster bots', 'Templates need version control like code'],
    evolution: evolutionItems([
      ['2025 Q4', 'Inbox MVP', 'done', 'Unified thread view shipped.'],
      ['2026 Q1', 'Omnichannel ingestion', 'in-progress', 'Email and chat connectors.'],
      ['2026 Q2', 'Sentiment v2', 'planned', 'Multilingual sentiment models.'],
      ['2026 Q3', 'CRM sync', 'planned', 'HubSpot and Salesforce connectors.'],
    ]),
    publishedAt: '2026-01-05',
  },
  ispmind: {
    industry: 'Telecommunications',
    headline: 'ISP operations when the network never sleeps',
    summary: 'Network monitoring, ticket automation and SLA dashboards for ISPs — 24/7 event processing on Engine.',
    problemTitle: 'ISP ops drowning in tickets and blind spots',
    problemNarrative: 'Regional ISPs ran on legacy ticketing with no network map, manual SLA tracking and outage detection that depended on customer calls — not telemetry.',
    painPoints: ['No live network topology view', 'Tickets classified manually', 'SLA breaches discovered late', 'NOC workflows fragmented'],
    solutionTitle: 'NOC platform on event-driven Engine',
    solutionNarrative: 'ISPMind ingests network events, classifies tickets with AI-OS and surfaces SLA risk in real time. Golden Screens validated NOC layouts with operator interviews before build.',
    approach: ['Network map with live status overlays', 'AI ticket classification', 'SLA countdown dashboards', '24/7 event processing in Engine'],
    architectureDecisions: ['Event stream as source of truth', 'Ticket AI suggests, humans confirm', 'SLA clocks immutable once started'],
    results: [{ value: '24/7', label: 'Event monitoring design' }, { value: '68%', label: 'Framework Health' }, { value: '↓ MTTR', label: 'Target for ticket automation' }],
    learnings: ['Telecom ops need 24/7 monitoring architecture', 'SLA tracking is a core data model, not a report', 'NOC UX must be validated with real operators'],
    evolution: evolutionItems([
      ['2025 Q4', 'Network Map prototype', 'done', 'Topology view with pilot ISP.'],
      ['2026 Q1', 'Telemetry ingestion', 'in-progress', 'SNMP and API collectors.'],
      ['2026 Q2', 'Ticket automation', 'planned', 'Classification and routing rules.'],
      ['2026 Q3', 'SLA dashboard', 'planned', 'Executive and NOC SLA views.'],
    ]),
    publishedAt: '2026-02-18',
  },
  'proodonto-smart': {
    industry: 'HealthTech',
    headline: 'Dental clinics deserve offline-tolerant scheduling',
    summary: 'Clinic management with smart scheduling, LGPD patient records and AI treatment insights — multi-clinic ready from architecture day one.',
    problemTitle: 'Clinic software that fails on no-shows and compliance',
    problemNarrative: 'Dental clinics lost revenue to no-shows, kept records in non-compliant silos and lacked treatment planning tools that integrated with scheduling.',
    painPoints: ['High no-show rates', 'Patient data compliance risk', 'Scheduling not offline-tolerant', 'Treatment planning disconnected from records'],
    solutionTitle: 'Multi-clinic health platform',
    solutionNarrative: 'ProOdonto Smart unifies scheduling, records and AI treatment suggestions with LGPD-by-design multi-tenancy. No-show prediction runs in AI-OS; reminders flow through Engine.',
    approach: ['Smart scheduling with prediction', 'LGPD multi-tenant patient records', 'Treatment AI with dentist approval', 'Offline-tolerant scheduling sync'],
    architectureDecisions: ['Clinic tenant isolation in Supabase', 'AI suggestions require dentist sign-off', 'Scheduling queue survives connectivity loss'],
    results: [{ value: '↓ No-shows', label: 'Prediction target' }, { value: '74%', label: 'Framework Health' }, { value: 'LGPD', label: 'Compliance by design' }],
    learnings: ['Clinics need offline-tolerant scheduling', 'Patient data demands compliance in schema', 'AI treatment hints must never auto-apply'],
    evolution: evolutionItems([
      ['2025 Q4', 'Clinic Dashboard Golden Screen', 'done', 'Validated with pilot clinic.'],
      ['2026 Q1', 'Smart scheduling', 'in-progress', 'Prediction and reminder engine.'],
      ['2026 Q2', 'Treatment planning AI', 'planned', 'Dentist-reviewed suggestions.'],
      ['2026 Q3', 'Patient portal', 'planned', 'Appointments and records access.'],
    ]),
    publishedAt: '2026-02-22',
  },
}

function buildCaseStudy(product: (typeof PRODUCT_CATALOG)[number]): CaseStudyContent {
  const extra = ENRICHMENTS[product.slug]
  if (!extra) {
    throw new Error(`Missing case study enrichment for ${product.slug}`)
  }
  return mergeEnrichment(product, extra)
}

export const CASE_STUDY_CATALOG: CaseStudyContent[] = PRODUCT_CATALOG.map(buildCaseStudy)

export function getCaseStudy(slug: string): CaseStudyContent | undefined {
  return CASE_STUDY_CATALOG.find((c) => c.slug === slug)
}

export function getCaseStudyPath(slug: string) {
  return `/cases/${slug}`
}
